_home:
    pattern:  /
    defaults: { _controller: tesisControltesisBundle:Default:index }
    
tesiscontroltesis:
    resource: "@tesisControltesisBundle/Resources/config/routing.yml"
    prefix:   /

