_home:
    pattern:  /
    defaults: { _controller: tesisControltesisBundle:Security:login }
    
tesiscontroltesis:
    resource: "@tesisControltesisBundle/Resources/config/routing.yml"
    prefix:   /

