tesis_controltesis_homepage:
    path:     /
    defaults: { _controller: tesisControltesisBundle:Default:index }

tesisControlAnnotations:
    resource: "@tesisControltesisBundle/Controller/"
    prefix: /
    type: annotation

login_check:
    pattern:  /login_check
    defaults: { _controller: tesisControltesisBundle:Security:securityCheck}

admin_login_check:
    pattern:  admin/login_check
    defaults: { _controller: tesisControltesisBundle:Security:securityCheck}

controltesis_homepage:
    path:     /init
    defaults: { _controller: tesisControltesisBundle:Default:inicio }

tesisControltesisBundle_usuario:
    resource: "@tesisControltesisBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

tesisControltesisBundle_etapa:
    resource: "@tesisControltesisBundle/Resources/config/routing/etapa.yml"
    prefix:   /etapa   

tesisControltesisBundle_asesoria:
    resource: "@tesisControltesisBundle/Resources/config/routing/asesoria.yml"
    prefix:   /asesoria

tesisControltesisBundle_tesisestado:
    resource: "@tesisControltesisBundle/Resources/config/routing/tesisestado.yml"
    prefix:   /tesisestado
    
admin_user:
    pattern:  /admin/user
    defaults: { _controller: "tesisControltesisBundle:User:index" }

admin_role:
    pattern:  /admin/role
    defaults: { _controller: "tesisControltesisBundle:Role:index" }

login_login_homepage:
    pattern:  /login
    defaults: { _controller: tesisControltesisBundle:Default:login }

login_login_signup:
    pattern:  /signup
    defaults: { _controller: tesisControltesisBundle:Default:signup }
    
login_login_logout:
    pattern:  /logout
    defaults: { _controller: tesisControltesisBundle:Security:loguot}

login_logout:
    pattern:  /admin/logout
    defaults: { _controller: tesisControltesisBundle:Security:loguot}
