tesis_controltesis_homepage:
    path:     /
    defaults: { _controller: tesisControltesisBundle:Default:index }

controltesis_homepage:
    path:     /init
    defaults: { _controller: tesisControltesisBundle:Default:inicio }

tesisControltesisBundle_usuario:
    resource: "@tesisControltesisBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

tesisControltesisBundle_etapa:
    resource: "@tesisControltesisBundle/Resources/config/routing/etapa.yml"
    prefix:   /etapa   

tesisControltesisBundle_asesoria:
    resource: "@tesisControltesisBundle/Resources/config/routing/asesoria.yml"
    prefix:   /asesoria

tesisControltesisBundle_tesisestado:
    resource: "@tesisControltesisBundle/Resources/config/routing/tesisestado.yml"
    prefix:   /tesisestado
    
login_login_homepage:
    pattern:  /login
    defaults: { _controller: tesisControltesisBundle:Default:index }

login_login_signup:
    pattern:  /signup
    defaults: { _controller: tesisControltesisBundle:Default:signup }
    
login_login_logout:
    pattern:  /logout
