tesis_controltesis_homepage:
    path:     /login
    defaults: { _controller: tesisControltesisBundle:Default:index }

tesisControltesisBundle_usuario:
    resource: "@tesisControltesisBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario