tesis_controltesis_homepage:
    path:     /login
    defaults: { _controller: tesisControltesisBundle:Default:index }

tesisControltesisBundle_usuario:
    resource: "@tesisControltesisBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

tesisControltesisBundle_etapa:
    resource: "@tesisControltesisBundle/Resources/config/routing/etapa.yml"
    prefix:   /etapa   

tesisControltesisBundle_asesoria:
    resource: "@tesisControltesisBundle/Resources/config/routing/asesoria.yml"
    prefix:   /asesoria  
    
tesisControltesisBundle_tesisestado:
    resource: "@tesisControltesisBundle/Resources/config/routing/tesisestado.yml"
    prefix:   /tesisestado      
    
